#!/usr/bin/env python3
"""Build a small simulation-to-visualization provenance campaign.

The payloads are intentionally plain text placeholders. HPC Campaign records
where products live; the PROV graph records how the logical scientific
products are related. Real applications register their ADIOS, HDF5, image, or
other datasets before making the same provenance calls shown here.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from hpc_campaign import Manager, VariableSpec


def _register_placeholder(manager: Manager, payload_dir: Path, name: str, variables: list[str]) -> None:
    """Register one stand-in for a payload produced outside the campaign."""

    path = payload_dir / f"{name}.txt"
    contents = "This is a placeholder for variables:\n"
    contents += "".join(f"- {variable}\n" for variable in variables)
    path.write_text(contents, encoding="utf-8")
    manager.text(path, name=name, store=True)


def build_example(  # pylint: disable=too-many-locals
    campaign_store: Path,
    archive: str = "provenance-example.aca",
) -> Path:
    """Create a small provenance graph and export it as PROV-JSON.

    The example deliberately separates two concerns: first, payloads are
    registered in the campaign; then provenance records describe the logical
    variables in those payloads and the activities that relate them. The
    returned path is the exported view of the graph. Its canonical copy remains
    stored in the campaign archive.
    """

    # Keep all generated files together and refuse to overwrite an existing
    # campaign so rerunning the example cannot silently discard prior work.
    campaign_store.mkdir(parents=True, exist_ok=True)
    archive_path = campaign_store / archive
    if archive_path.exists():
        raise FileExistsError(f"refusing to replace existing campaign: {archive_path}")

    # These text files stand in for data products generated by external tools.
    # Provenance variables may refer only to datasets already known to the
    # campaign, just as they would refer to registered ADIOS, HDF5, or images.
    payload_dir = campaign_store / f"{Path(archive).stem}-payloads"
    payload_dir.mkdir(parents=True, exist_ok=True)

    manager = Manager(archive=archive, campaign_store=str(campaign_store))
    manager.open(create=True)
    try:
        datasets = {
            "simulation-output": ["P"],
            "reduced-products": ["P_reduced"],
            "qoi-products": ["total_pressure"],
            "visualizations": ["pressure.png"],
        }
        for dataset, variables in datasets.items():
            _register_placeholder(manager, payload_dir, dataset, variables)

        # Agents identify responsible software, while Plans identify recipes or
        # configurations. The run associates both with a SimulationRun Activity.
        sim = manager.add_agent("software", "sim", version="example")
        run_plan = manager.add_plan(
            "sim input configuration",
            location="inputs/run-001.yaml",
        )
        run = manager.add_run("run-001", agent=sim, plan=run_plan)

        # A logical variable is a scientific Entity, not a copy of its payload.
        # This record says that run-001 generated pressure variable P, whose
        # bytes are found in the registered simulation-output dataset.
        pressure = manager.add_variable(
            run=run,
            dataset="simulation-output",
            variable="P",
            definition="pressure",
            units="Pa",
            coordinate_system="boozer",
        )

        # add_activity() atomically records an Activity, its input usages, its
        # output generations, and output-to-input derivations. VariableSpec
        # describes a new output Entity; the returned ActivityResult exposes its
        # stable reference for use by later stages.
        mgard = manager.add_agent("software", "MGARD", version="example")
        reduced = manager.add_activity(
            "reduction",
            inputs={"source": pressure},
            outputs={
                "result": VariableSpec(
                    run=run,
                    dataset="reduced-products",
                    variable="P_reduced",
                    definition="pressure",
                    units="Pa",
                    coordinate_system="boozer",
                )
            },
            action_spec={"method": "mgard", "error_bound": 0.001},
            agent=mgard,
        )

        # Chaining the reduction's output into this input extends the graph:
        # pressure -> reduction -> reduced pressure -> QoI -> total pressure.
        # A quantity of interest may be an array or a scalar; here it is a total.
        analysis = manager.add_agent("software", "QoI analysis", version="example")
        total_pressure = manager.add_activity(
            "quantity_of_interest",
            inputs={"pressure": reduced.outputs["result"]},
            outputs={
                "total": VariableSpec(
                    run=run,
                    dataset="qoi-products",
                    variable="total_pressure",
                    definition="total_pressure",
                    units="Pa",
                )
            },
            action_spec={"operation": "sum"},
            agent=analysis,
        )

        # The reduced pressure and total pressure are scientific inputs to the
        # visualization, so the image is derived from both. The Fides model is
        # context: it guides the activity but is not scientific source data and
        # therefore must not become a derivation parent.
        paraview = manager.add_agent("software", "ParaView", version="example")
        fides = manager.add_plan(
            "Fides data model",
            location="visualization/fides.json",
        )
        image = manager.add_activity(
            "visualization",
            inputs={
                "color": reduced.outputs["result"],
                "annotation": total_pressure.outputs["total"],
            },
            context={"data_model": fides},
            outputs={
                "image": VariableSpec(
                    run=run,
                    dataset="visualizations",
                    variable="pressure.png",
                    definition="pressure_visualization",
                )
            },
            action_spec={"representation": "isosurface", "colormap": "viridis"},
            agent=paraview,
            plan=fides,
        )

        # Provenance calls above update the canonical document inside the ACA.
        # Exporting writes an interoperable PROV-JSON snapshot for inspection or
        # use by standard W3C PROV tooling; it does not move provenance out of
        # the campaign.
        export_path = campaign_store / "provenance-example.json"
        manager.export_prov("campaign-provenance", export_path)
        print(f"Campaign: {archive_path}")
        print(f"Final image logical variable: {image.outputs['image']}")
        print(f"PROV-JSON export: {export_path}")
        return export_path
    finally:
        manager.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "campaign_store",
        type=Path,
        help="directory in which to create the example ACA and payloads",
    )
    parser.add_argument("--archive", default="provenance-example.aca")
    args = parser.parse_args()
    build_example(args.campaign_store, args.archive)


if __name__ == "__main__":
    main()
